# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.processing_job import ProcessingJob

class RequiredGetProcessingJobsResponse(TypedDict):
    pass

class OptionalGetProcessingJobsResponse(TypedDict, total=False):
    # The job ID of the receiving job that spawned this job.
    parentJobId: str

    # The tenant code of the receiving job that spawned this job.
    parentTenantCode: str

    # The limit of processing jobs to retrieve per page.
    limit: int

    # The index to start retrieving results from, also known as offset. The index begins at 0.
    start: int

    # A list of objects representing the processing jobs to retrieve.
    processingJobs: typing.List[ProcessingJob]

class GetProcessingJobsResponse(RequiredGetProcessingJobsResponse, OptionalGetProcessingJobsResponse):
    pass
