# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJob(TypedDict):
    pass

class OptionalJob(TypedDict, total=False):
    # The job ID of the receiving job for the analytic tenant.
    receivingJobId: str

    # The analytic tenant code.
    tenantCode: str

    # The status of the receiving job for the analytic tenant.
    status: str

class Job(RequiredJob, OptionalJob):
    pass
