# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.push_data_column_definition_dto_data_formats import PushDataColumnDefinitionDTODataFormats

class RequiredPushDataColumnDefinitionDTO(TypedDict):
    pass

class OptionalPushDataColumnDefinitionDTO(TypedDict, total=False):
    # The name of the column.
    columnName: str

    # The data type associated with the column.
    dataType: str

    dataFormats: PushDataColumnDefinitionDTODataFormats

    # If true, the column value is required. If a column is mandatory, and the file is missing this column, the request will fail.
    isMandatory: bool

    # If true, the column allows an empty value for the record.
    allowEmpty: bool

    # The default value of the column.
    defaultValue: str

class PushDataColumnDefinitionDTO(RequiredPushDataColumnDefinitionDTO, OptionalPushDataColumnDefinitionDTO):
    pass
