# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPushDataCompleteRequest(TypedDict):
    pass

class OptionalPushDataCompleteRequest(TypedDict, total=False):
    # The unique identifier associated with the transfer session.
    transferSessionId: str

    # If true, a processing job will be triggered after the receiving job successfully completes. This generates a new data version.
    processingData: bool

class PushDataCompleteRequest(RequiredPushDataCompleteRequest, OptionalPushDataCompleteRequest):
    pass
