# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.push_data_source_definition_dto import PushDataSourceDefinitionDTO

class RequiredPushDataSourceDefinitionsDTO(TypedDict):
    pass

class OptionalPushDataSourceDefinitionsDTO(TypedDict, total=False):
    # A list of objects representing the target sources for the request.
    sources: typing.List[PushDataSourceDefinitionDTO]

class PushDataSourceDefinitionsDTO(RequiredPushDataSourceDefinitionsDTO, OptionalPushDataSourceDefinitionsDTO):
    pass
