# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.push_data_column_definition_dto import PushDataColumnDefinitionDTO

class RequiredPushDataSourceDefinitionDTO(TypedDict):
    pass

class OptionalPushDataSourceDefinitionDTO(TypedDict, total=False):
    # The unique identifier associated with the source.
    sourceId: str

    # The object name of the source.
    name: str

    # A list of objects representing the source columns.
    columns: typing.List[PushDataColumnDefinitionDTO]

    # If true, the source is inherited by all analytic tenants.
    isInherited: bool

class PushDataSourceDefinitionDTO(RequiredPushDataSourceDefinitionDTO, OptionalPushDataSourceDefinitionDTO):
    pass
