# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.tenant import Tenant

class RequiredPushDataResponse(TypedDict):
    pass

class OptionalPushDataResponse(TypedDict, total=False):
    # The unique identifier associated with the transfer session.
    transferSessionId: str

    # The unique sequence number associated with a batch of records.
    sequence: int

    # The status of the data transfer.
    status: str

    # Any additional information about the data transfer.
    message: str

    # A list of strings representing the tenants that data was pushed to and their data transfer results.
    tenants: typing.List[Tenant]

class PushDataResponse(RequiredPushDataResponse, OptionalPushDataResponse):
    pass
