# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.data_transfer_result_detail import DataTransferResultDetail

class RequiredPushDataCancelResponse(TypedDict):
    pass

class OptionalPushDataCancelResponse(TypedDict, total=False):
    # A meaningful message about the transfer session.
    message: str

    # The unique identifier associated with the transfer session.
    transferSessionId: str

    # A list of objects representing the results of the transfer session.
    dataTransferResultDetails: typing.List[DataTransferResultDetail]

    # The status of the transfer session. A cancelled session returns the status CANCELLED.
    status: str

class PushDataCancelResponse(RequiredPushDataCancelResponse, OptionalPushDataCancelResponse):
    pass
