# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.job import Job

class RequiredReceivingJobStatusResponse(TypedDict):
    pass

class OptionalReceivingJobStatusResponse(TypedDict, total=False):
    # The unique identifier associated with the receiving job.
    jobId: str

    # The status of the receiving job.
    status: str

    # The job ID of the receiving job that spawned this job.
    parentJobId: str

    # The tenant code of the receiving job that spawned  this job.
    parentTenantCode: str

    # A list of objects representing the receiving jobs to retrieve.
    receivingJobs: typing.List[Job]

class ReceivingJobStatusResponse(RequiredReceivingJobStatusResponse, OptionalReceivingJobStatusResponse):
    pass
