# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSource(TypedDict):
    pass

class OptionalSource(TypedDict, total=False):
    # The unique identifier associated with the source that data was transferred to.
    sourceId: str

    # The object name of the source.
    sourceName: str

    # The size of the data transfer in bytes.
    dataSize: str

    # The number of rows in the data transfer.
    rows: str

    # The status of the data transfer for this source.
    status: str

    # A meaningful message about the data transfer.
    message: str

class Source(RequiredSource, OptionalSource):
    pass
