# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from visier_data_intake_python_sdk.type.source import Source

class RequiredTenant(TypedDict):
    pass

class OptionalTenant(TypedDict, total=False):
    # The code of the tenant that data was transferred to. For example, WFF_j1r or WFF_j1r~c7o.
    tenantCode: str

    # The status of the data transfer for this tenant.
    status: str

    # A list of objects representing the sources that data was pushed to and their data transfer results.
    sources: typing.List[Source]

class Tenant(RequiredTenant, OptionalTenant):
    pass
