# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_data_intake_python_sdk.paths.v1alpha_data_upload_files_filename.put import FileToVisierRaw


class DataUploadApiRaw(
    FileToVisierRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
