# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_data_intake_python_sdk.paths.v1alpha_data_upload_files_filename.put import FileToVisier
from visier_data_intake_python_sdk.apis.tags.data_upload_api_raw import DataUploadApiRaw


class DataUploadApi(
    FileToVisier,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DataUploadApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DataUploadApiRaw(api_client)
