# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_data_intake_python_sdk.paths.v1_op_jobs_processing_jobs_receiving_job_id.get import GetProcessingJobsByParentReceivingJobIdRaw
from visier_data_intake_python_sdk.paths.v1_op_data_sources.get import GetSourcesRaw
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions_transfer_session_id_add.put import PushDataRaw
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions_transfer_session_id_cancel.put import PushDataCancelRaw
from visier_data_intake_python_sdk.paths.v1_op_jobs_receiving_jobs.post import PushDataCompleteRaw
from visier_data_intake_python_sdk.paths.v1_op_jobs_receiving_jobs_receiving_job_id.get import ReceivingJobStatusRaw
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions.post import StartTransferRaw
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions_transfer_session_id_upload.put import UploadDataRaw


class DataIntakeApiRaw(
    GetProcessingJobsByParentReceivingJobIdRaw,
    GetSourcesRaw,
    PushDataRaw,
    PushDataCancelRaw,
    PushDataCompleteRaw,
    ReceivingJobStatusRaw,
    StartTransferRaw,
    UploadDataRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
