# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from visier_data_intake_python_sdk.paths.v1_op_jobs_processing_jobs_receiving_job_id.get import GetProcessingJobsByParentReceivingJobId
from visier_data_intake_python_sdk.paths.v1_op_data_sources.get import GetSources
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions_transfer_session_id_add.put import PushData
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions_transfer_session_id_cancel.put import PushDataCancel
from visier_data_intake_python_sdk.paths.v1_op_jobs_receiving_jobs.post import PushDataComplete
from visier_data_intake_python_sdk.paths.v1_op_jobs_receiving_jobs_receiving_job_id.get import ReceivingJobStatus
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions.post import StartTransfer
from visier_data_intake_python_sdk.paths.v1_op_data_transfer_sessions_transfer_session_id_upload.put import UploadData
from visier_data_intake_python_sdk.apis.tags.data_intake_api_raw import DataIntakeApiRaw


class DataIntakeApi(
    GetProcessingJobsByParentReceivingJobId,
    GetSources,
    PushData,
    PushDataCancel,
    PushDataComplete,
    ReceivingJobStatus,
    StartTransfer,
    UploadData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DataIntakeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DataIntakeApiRaw(api_client)
