# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

import unittest

import visier_data_intake_python_sdk
from visier_data_intake_python_sdk.model.push_data_column_definition_dto import PushDataColumnDefinitionDTO
from visier_data_intake_python_sdk import configuration


class TestPushDataColumnDefinitionDTO(unittest.TestCase):
    """PushDataColumnDefinitionDTO unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
