# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ProcessingJob(BaseModel):
    # The job ID of the processing job for the analytic tenant.
    job_id: typing.Optional[str] = Field(None, alias='jobId')

    # The analytic tenant code.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # The data version associated with the processing job.
    data_version: typing.Optional[str] = Field(None, alias='dataVersion')

    # The status of the receiving job for the analytic tenant.
    status: typing.Optional[str] = Field(None, alias='status')

    # A meaningful message about the processing job.
    message: typing.Optional[str] = Field(None, alias='message')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
