# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from visier_data_intake_python_sdk.pydantic.push_data_source_definition_dto import PushDataSourceDefinitionDTO

class PushDataSourceDefinitionsDTO(BaseModel):
    # A list of objects representing the target sources for the request.
    sources: typing.Optional[typing.List[PushDataSourceDefinitionDTO]] = Field(None, alias='sources')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
