# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from visier_data_intake_python_sdk.pydantic.push_data_column_definition_dto import PushDataColumnDefinitionDTO

class PushDataSourceDefinitionDTO(BaseModel):
    # The unique identifier associated with the source.
    source_id: typing.Optional[str] = Field(None, alias='sourceId')

    # The object name of the source.
    name: typing.Optional[str] = Field(None, alias='name')

    # A list of objects representing the source columns.
    columns: typing.Optional[typing.List[PushDataColumnDefinitionDTO]] = Field(None, alias='columns')

    # If true, the source is inherited by all analytic tenants.
    is_inherited: typing.Optional[bool] = Field(None, alias='isInherited')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
