# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PushDataCompleteRequest(BaseModel):
    # The unique identifier associated with the transfer session.
    transfer_session_id: typing.Optional[str] = Field(None, alias='transferSessionId')

    # If true, a processing job will be triggered after the receiving job successfully completes. This generates a new data version.
    processing_data: typing.Optional[bool] = Field(None, alias='processingData')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
