# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from visier_data_intake_python_sdk.pydantic.source import Source

class Tenant(BaseModel):
    # The code of the tenant that data was transferred to. For example, WFF_j1r or WFF_j1r~c7o.
    tenant_code: typing.Optional[str] = Field(None, alias='tenantCode')

    # The status of the data transfer for this tenant.
    status: typing.Optional[str] = Field(None, alias='status')

    # A list of objects representing the sources that data was pushed to and their data transfer results.
    sources: typing.Optional[typing.List[Source]] = Field(None, alias='sources')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
