# coding: utf-8

"""
    Visier Data Intake APIs

    Visier APIs for sending raw or untransformed source data to Visier

    The version of the OpenAPI document: 22222222.99201.1200
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from visier_data_intake_python_sdk import schemas  # noqa: F401


class ReceivingJobStatusResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            jobId = schemas.StrSchema
            status = schemas.StrSchema
            parentJobId = schemas.StrSchema
            parentTenantCode = schemas.StrSchema
            
            
            class receivingJobs(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Job']:
                        return Job
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['Job'], typing.List['Job']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'receivingJobs':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Job':
                    return super().__getitem__(i)
            __annotations__ = {
                "jobId": jobId,
                "status": status,
                "parentJobId": parentJobId,
                "parentTenantCode": parentTenantCode,
                "receivingJobs": receivingJobs,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["jobId"]) -> MetaOapg.properties.jobId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["parentJobId"]) -> MetaOapg.properties.parentJobId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["parentTenantCode"]) -> MetaOapg.properties.parentTenantCode: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["receivingJobs"]) -> MetaOapg.properties.receivingJobs: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["jobId", "status", "parentJobId", "parentTenantCode", "receivingJobs", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["jobId"]) -> typing.Union[MetaOapg.properties.jobId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> typing.Union[MetaOapg.properties.status, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["parentJobId"]) -> typing.Union[MetaOapg.properties.parentJobId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["parentTenantCode"]) -> typing.Union[MetaOapg.properties.parentTenantCode, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["receivingJobs"]) -> typing.Union[MetaOapg.properties.receivingJobs, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["jobId", "status", "parentJobId", "parentTenantCode", "receivingJobs", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        jobId: typing.Union[MetaOapg.properties.jobId, str, schemas.Unset] = schemas.unset,
        status: typing.Union[MetaOapg.properties.status, str, schemas.Unset] = schemas.unset,
        parentJobId: typing.Union[MetaOapg.properties.parentJobId, str, schemas.Unset] = schemas.unset,
        parentTenantCode: typing.Union[MetaOapg.properties.parentTenantCode, str, schemas.Unset] = schemas.unset,
        receivingJobs: typing.Union[MetaOapg.properties.receivingJobs, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ReceivingJobStatusResponse':
        return super().__new__(
            cls,
            *args,
            jobId=jobId,
            status=status,
            parentJobId=parentJobId,
            parentTenantCode=parentTenantCode,
            receivingJobs=receivingJobs,
            _configuration=_configuration,
            **kwargs,
        )

from visier_data_intake_python_sdk.model.job import Job
